# Keep only this one (the user_db one from line 21)
spring.datasource.url=jdbc:h2:file:./data/user_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
jwt.secretKey=EcIa71V3nTxDO+iXXaizPiv9BnPF26l2gxmaX4UEPogIWuyFE65cCD9B+9O35PPfsRTzdZ25r0vw9o7T76vNXg==
jwt.expirationMs=86400000

spring.main.allow-bean-definition-overriding=true

#USDA api key 4/23/2026 needed for accessing public api from USDA food
usda.api.key=TcL6aDaU9xZ6B8hb5uLdTZ5f0WQI61TW02Th7Zlz